Angular/Drawer template styling
ADjenkov/UIKitsTemplates pull request #5
Opened 2017-05-18 14:56 UTC by vegeorgi

2017-05-19 11:27 UTC, MartoYankov requested changes
bump

2017-05-19 11:27 UTC, MartoYankov commented on Angular/DrawerNavigation/app/browse/browse.component.html
> +                <MyDrawer [selectedPage]="'Browse'"></MyDrawer>
a minor indentation problem? It's on every page.

2017-05-19 11:27 UTC, MartoYankov commented on Angular/DrawerNavigation/app/shared/drawer.component.html
> +                    [class.selected]="item.title===selectedPage">
According to Angular guidelines, this shouldn't be here. There should be no presentation logic in the markup.

"Do put presentation logic in the component class, and not in the template."

2017-05-22 08:41 UTC, vegeorgi commented on Angular/DrawerNavigation/app/browse/browse.component.html
> +                <MyDrawer [selectedPage]="'Browse'"></MyDrawer>
Done :)

2017-05-22 08:41 UTC, vegeorgi commented on Angular/DrawerNavigation/app/shared/drawer.component.html
> +                    [class.selected]="item.title===selectedPage">
Done :)

2017-05-23 07:43 UTC, ADjenkov approved these changes

2017-05-29 08:33 UTC, merged